name: push
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "::add-mask::${{ secrets.STEAMPULL_USER }}"
          echo "::add-mask::${{ secrets.STEAMPULL_PASSWD }}"
          echo "::add-mask::${{ secrets.STEAMPULL_SECRET }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt

      - env:
          STEAMPULL_USER: ${{ secrets.STEAMPULL_USER }}
          STEAMPULL_PASSWD: ${{ secrets.STEAMPULL_PASSWD }}
          STEAMPULL_SECRET: ${{ secrets.STEAMPULL_SECRET }}
        run: ./steampull auth
      - run: ls
      - run: ./steampull --app 238960 --depot 238961 --output build fetch --regex "Bundles2\\\\_\.index"
      - run: ls build
      - run: ls build/depot
      - run: ls build/depot/Bundles2
      - run: ./steampull --app 238960 --depot 238961 --output build fetch --regex "Bundles2\\\\_\.index"
  test-windows:
    runs-on: windows-latest

    steps:
      - run: |
          echo "::add-mask::${{ secrets.STEAMPULL_USER }}"
          echo "::add-mask::${{ secrets.STEAMPULL_PASSWD }}"
          echo "::add-mask::${{ secrets.STEAMPULL_SECRET }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements-win.txt

      - env:
          STEAMPULL_USER: ${{ secrets.STEAMPULL_USER }}
          STEAMPULL_PASSWD: ${{ secrets.STEAMPULL_PASSWD }}
          STEAMPULL_SECRET: ${{ secrets.STEAMPULL_SECRET }}
        run: bash -c './steampull auth'
      - run: ls
      # backslashes\\\\\\\\ are a bit ridiculous here, but it works
      - run: bash -c './steampull --app 238960 --depot 238961 --output build fetch --regex "Bundles2\\\\\\\\_\\.index"'
      - run: ls build
      - run: ls build/depot
      - run: ls build/depot/Bundles2
      - run: bash -c './steampull --app 238960 --depot 238961 --output build fetch --regex "Bundles2\\\\\\\\_\\.index"'
