#!/bin/sh -eux
game=${1-game}
cp "$game"/mods/active/*.as ch2data/
ffdec -export script build/ClickerHeroes2 "$game"/ClickerHeroes2.swf
cp build/ClickerHeroes2/scripts/models/Character.as ch2data/
cp build/ClickerHeroes2/scripts/heroclickerlib/managers/Formulas.as ch2data/
cp build/ClickerHeroes2/scripts/heroclickerlib/CH2.as ch2data/
