#!/bin/sh -eux
# assumptions:
# * clicker heroes 2 is symlinked (or installed?) to <this-repo>/game
# * the flex sdk is installed (for mxmlc) - https://www.adobe.com/devnet/flex/flex-sdk-download.html
#
# Run me, copy the json from the browser console into gedit, and ctrl-c the server when done.
# Ctrl-c to kill the server afterward is important - there's some post-processing done then.

rm -rf build/chars
mkdir -p build/chars

for f in `pwd`/game/mods/active/*.swf; do
  ln -s $f build/chars
done
ln -s `pwd`/game/ClickerHeroes2.swf build/chars
ls build/chars
mxmlc src/CharToJson.as -output build/chars/CharToJson.swf
cp src/CharToJson.html build/chars/index.html

rm -f assets/ch2data/chars/latest.json
gedit assets/ch2data/chars/latest.json &
# https://stackoverflow.com/questions/14702148/how-to-fire-a-command-when-a-shell-script-is-interrupted
onExit() {
  trap INT
  ./scripts/export/postchars assets/ch2data/chars/latest.json
}
trap onExit INT
serve build/chars
