#!/bin/sh -eux
# I expect the Clicker Heroes 2 game to be extracted to `./game`. I'm not going to autodownload the 2gb thing in this script.
mkdir -p build/extract
# don't re-extract unless the swc is newer, because it takes ages
if [ ! ./build/extract/Essentials_MEDIUM_ATF -nt ./game/packer/src/exports/Essentials_MEDIUM_ATF.swc ]; then
  unzip -o ./game/packer/src/exports/Essentials_MEDIUM_ATF.swc -d ./build/extract/Essentials_MEDIUM_ATF
  ffdec -export sprite ./build/extract/Essentials_MEDIUM_ATF/sprites ./build/extract/Essentials_MEDIUM_ATF/library.swf
fi
if [ ! ./build/extract/BitmapHUD_HIGH_PNG -nt ./game/packer/src/exports/Essentials_MEDIUM_ATF.swc ]; then
  unzip -o ./game/packer/src/exports/BitmapHUD_HIGH_PNG.swc -d ./build/extract/BitmapHUD_HIGH_PNG
  ffdec -export sprite ./build/extract/BitmapHUD_HIGH_PNG/sprites ./build/extract/BitmapHUD_HIGH_PNG/library.swf
fi

mkdir -p ./assets/ch2data/img
for icon in starBG; do
  cp -p ./build/extract/Essentials_MEDIUM_ATF/sprites/*_${icon}_*/*.png ./assets/ch2data/img/$icon.png
done
for icon in generalNode specialNode deluxeNode; do
  convert ./build/extract/Essentials_MEDIUM_ATF/sprites/*_${icon}_*/1.png -transparent black ./assets/ch2data/img/$icon.png
done
for icon in `./list-icons.js ./assets/ch2data/chars/latest.json`; do
  convert ./build/extract/Essentials_MEDIUM_ATF/sprites/*_${icon}_*/*.png -transparent black ./assets/ch2data/img/$icon.png
done
mkdir -p ./assets/ch2data/img/skills
cp -rp build/extract/BitmapHUD_HIGH_PNG/sprites/*UpgradeIcons*/* ./assets/ch2data/img/skills/
