name: assets-export
on:
  schedule:
    - cron: "5 1 * * *"
  workflow_dispatch:

jobs:
  # windows must run this, not ubuntu, as we must run ch2.exe to complete our export and it doesn't run on linux.
  fetch:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          echo "::add-mask::${{ secrets.STEAMCTL_USER }}"
          echo "::add-mask::${{ secrets.STEAMCTL_PASSWD }}"
          echo "::add-mask::${{ secrets.STEAMCTL_SECRET }}"
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - working-directory: ./assets-dl
        run: yarn fetch:install
      - working-directory: ./assets-dl
        env:
          STEAMPULL_USER: ${{ secrets.STEAMCTL_USER }}
          STEAMPULL_PASSWD: ${{ secrets.STEAMCTL_PASSWD }}
          STEAMPULL_SECRET: ${{ secrets.STEAMCTL_SECRET }}
        run: yarn fetch:auth
      - working-directory: ./assets-dl
        run: yarn fetch

      - working-directory: ./assets-dl
        run: |
          echo 'STEAM_DEPOT_INFO_NEW<<__EOF__' >> $GITHUB_ENV
          cat info.txt >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV
      - working-directory: ./assets-dl
        run: |
          echo 'STEAM_DEPOT_INFO_DIFF<<__EOF__' >> $GITHUB_ENV
          (diff info-old.txt info.txt || true) >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV
      ## Stop running if there's no info.txt differences
      ## If PRs ever stop working, we could create an issue instead:
      #- if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
      #  uses: JasonEtco/create-an-issue@v2
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    filename: .github/ggpk-notify-issue-template.md
      #    update_existing: true

      # https://github.com/marketplace/actions/setup-java-jdk
      # ffdec needs this (flash decompiler, in `yarn as3`)
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: yarn --frozen-lockfile
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        working-directory: ./assets
        run: yarn ffdec:install

      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        working-directory: ./assets
        run: yarn as3

      # TODO: install the ch2 mod /exporter/bin/ch2plan-exporter.swf, run ch2,
      # and copy the "latest.json" file it exports.
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: cp exporter/bin/ch2plan-exporter.swf assets-dl/depot/mods/active/
      # add our mod to mods.txt, per the ch2-mods docs - but we've never run ch2 on this machine before, so we have to create mods.txt from scratch
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: ls -l "c:\\Users\\runneradmin\\AppData\\Roaming"
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: mkdir -p "c:\\Users\\runneradmin\\AppData\\Roaming\\ClickerHeroes2\\Local Store\\"
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: cp "./.github/workflows/assets-export-mods.txt" "c:\\Users\\runneradmin\\AppData\\Roaming\\ClickerHeroes2\\Local Store\\mods.txt"

      # Start CH2, let the 1-minute timeout kill the process, and keep going.
      # 1 minute is plenty of time for ch2plan-exporter to do its thing.
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: ls -l "c:\\Users\\runneradmin\\Desktop"
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        working-directory: ./assets-dl/depot
        run: ./ClickerHeroes2.exe
        timeout-minutes: 1
        continue-on-error: true
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: sleep 10
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: ls -l "c:\\Users\\runneradmin\\AppData\\Roaming\\ClickerHeroes2\\Local Store\\"
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: ls -l "c:\\Users\\runneradmin\\Desktop"
      # TODO: this didn't work - ch2 never actually ran on the ci machine! I don't know why.
      #- if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
      #  run: ls -l "c:\\Users\\runneradmin\\Desktop\\latest.json"

      # TODO: `yarn build` won't work until we get the above working.
      # by installing the ch2 mod before running ch2.
      #- if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
      #  working-directory: ./assets
      #  run: yarn build

      # https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflows-assets-export
          commit-message: '[assets-export] CH2 content updates'
          title: '[assets-export] CH2 content updates'
          body: >
            Looks like Clicker Heroes 2 was patched recently! I've updated ch2plan for you.

            Sadly, I'm not smart enough to auto-update everything. You might need to update [stats.json5](https://github.com/erosson/ch2plan/blob/master/assets/stats.json5) by hand: read the developers' patch notes and the `.as` files I've exported here. Run `cd assets && yarn build` when done. (None of that requires installing any of the arcane flash tools, just nodejs.)

            This PR is auto-generated by the [assets-export robot](https://github.com/erosson/ch2plan/actions?query=workflow%3Aassets-export).
          labels: automated pr
