name: wsl-test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: whoami
      - run: ls -l /
      - run: ls -l "c:"
      - run: ls -l "c:\Users\"
      - run: ls -l "c:\Users\runneradmin"
      - run: ls -l "c:\Users\runneradmin\AppData"
      - run: ls -l "c:\Users\runneradmin\AppData\Roaming"
      # - run: ls -l "/c/Users/`whoami`/AppData/Roaming/ClickerHeroes2/Local Store/"
      # - run: ls -l "/c/Users/`whoami`/AppData/Roaming/ClickerHeroes2/Local Store/"
